Updated function and test
UBC-MDS/PrepR pull request #49
Opened 2020-03-10 15:49 UTC by gptzjs

Updated function to output a list of dataframes (x6) and test to check dimensions of each dataframe

2020-03-12 17:20 UTC, jasmineqyj requested changes
This looks good! Just updating a typo in the test file.

- Just a reminder that we need to add `gensvm` as a dependency.

2020-03-12 17:20 UTC, jasmineqyj commented on tests/testthat/test-train_valid_test_split.R
> +  expect_true(dim(ouput$y_test)[1] == 2)
```suggestion
  expect_true(dim(output$y_valid)[1] == 2)
  expect_true(dim(output$y_test)[1] == 2)
```

2020-03-13 00:20 UTC, matthewconnell approved these changes

2020-03-13 00:21 UTC, matthewconnell approved these changes

2020-03-13 00:22 UTC, matthewconnell approved these changes

2020-03-13 00:40 UTC, gptzjs commented
@jasmineqyj  @matthewconnell has added `gensvm` as a dependency in `DESCRIPTION`

2020-03-13 00:40 UTC, closed without merging